name = "canyourunai-quantize"
type = "typescript"
compatibility_date = "2025-02-05"

# Specify the entry point for your new worker
main = "src/index.ts"

kv_namespaces = [
  { binding = "SYSTEM_INFO", id = "097faddb5ea74a6cb856d604fda8dc2e", preview_id = "b145afab1c7545688759ba64a5111e36" }
]


# Optionally add a route to avoid conflicts:
# route = "quantize.example.com/*"
