name: Update GPU Database

on:
  schedule:
    - cron: '0 0 1 * *'  # Run monthly
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-gpu-db:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium
          npm install wrangler
          
      - name: Run GPU scraper
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          source .venv/bin/activate
          python scripts/gpu_scraper/scrape_gpus.py 